version: '3'
services:
  db:
    image: postgres:14
    # volumes:
    #   - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ntr
    ports:
      - "5432:5432"
