version: '3'
services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ntr
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - $PWD:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
